apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: wordpress
spec:
  endpoints:
  - interval: 15s
    port: mysql-exporter
#  namespaceSelector:
#    any: true
#    matchNames:
#      - wordpress
  selector:
    matchLabels:
      app: mysql-service
