apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress-exporter
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wp-service
#  namespaceSelector:
#    any: true
  endpoints:
  - port: wp-exporter
